# サイトのタイトル（任意の名前）
title: "My GitHub Pages Site"

# GitHub PagesのリポジトリURL
url: "https://pan049.github.io/pan"

# ビルド出力先
destination: ./_site

# markdownのエンジン
markdown: kramdown

# CSSなどの静的ファイルのパス設定
sass:
  style: compressed
  sass_dir: assets/css

# ビルドのソースディレクトリ
source: docs

# 使用するテーマ
theme: minima
